contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #snomics channel"
    url: https://nfcore.slack.com/channels/snomics
    about: Discussion about the nf-core/snomics pipeline
